# Generated by Django 3.0.3 on 2020-05-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg',
        ),
    ]
