# Generated by Django 3.0.3 on 2020-02-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='kms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
