# Generated by Django 3.0.3 on 2020-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200224_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel_no',
            field=models.CharField(default=0, max_length=18),
        ),
    ]
