# Generated by Django 3.0.3 on 2020-02-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200224_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
