# Generated by Django 3.0.3 on 2020-02-26 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_trip_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='rider',
        ),
        migrations.AddField(
            model_name='trip',
            name='rider',
            field=models.ManyToManyField(blank=True, null=True, related_name='trips_as_rider', to=settings.AUTH_USER_MODEL),
        ),
    ]
