# Generated by Django 3.0.3 on 2020-02-27 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200226_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='rider',
            field=models.ManyToManyField(blank=True, related_name='trips_as_rider', to=settings.AUTH_USER_MODEL),
        ),
    ]
