# Generated by Django 3.0.3 on 2020-02-27 07:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_trip_geo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='to_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
