# Generated by Django 3.0.3 on 2020-02-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_trip_to_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='geo_location_lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='geo_location_long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
