# Generated by Django 3.0.3 on 2020-03-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='take_off_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
