# Generated by Django 3.0.3 on 2020-03-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_trip_take_off_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='take_off_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
