# Generated by Django 3.0.3 on 2020-03-02 14:34

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200302_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='UTC', null=True),
        ),
    ]
