# Generated by Django 3.0.3 on 2020-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_trip_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='drop_lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='drop_lng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
