# Generated by Django 3.0.3 on 2020-03-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200309_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='take_off',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='take_off_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
